<a href="https://colab.research.google.com/github/PalakCode1/BIG_DATA_Assignments/blob/main/labEval_group2_202301042.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

arr_1 = np.array([10,52,62,16,16,54,453])

#sorting
sort_arr = np.sort(arr_1)
print(sort_arr)

#indicing
#smallest element
#largest element



[ 10  16  16  52  54  62 453]


In [8]:
arr_1_indicing= np.argsort(sort_arr)
print(arr_1_indicing)

[0 1 2 3 4 5 6]


In [11]:
smallest_elements = np.min(sort_arr)
print(smallest_elements)

10


In [12]:
largest_element = np.max(sort_arr)
print(largest_element)

453


In [18]:
smallest=sort_arr[:4]
print(smallest)


[10 16 16 52]
